keys:
  - &steamdeck_willy ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
  - &thenixbeast ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEB74qOTioDeqED1VPlfAHWsQuh5x5TQs7kji2S8QiEM
  - &thenixbeast_will ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
creation_rules:
  - path_regex: hosts/steamdeck/secrets.yaml
    key_groups:
      - age:
        - *steamdeck_willy
        - *thenixbeast_will
  - path_regex: hosts/thenixbeast/secrets.yaml
    key_groups:
      - age:
        - *thenixbeast
        - *steamdeck_willy
        - *thenixbeast_will
  - path_regex: modules/distributed_builders/secrets.yaml
    key_groups:
      - age:
        - *thenixbeast
        - *steamdeck_willy
        - *thenixbeast_will
stores:
  yaml:
    indent: 2
