[theme]
theme = "solarized-dark"
[icons]
icons = "awesome4"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "$icon  $used/$total "

[[block]]
block = "memory"
format = "$icon $mem_used.eng(w:1)/$mem_total.eng(w:1) "

[[block]]
block = "cpu"

[[block]]
block = "load"
interval = 5

[[block]]
block = "music"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "$icon  $percentage "

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R')"
